import { defineManifest } from "@crxjs/vite-plugin";
import packageJson from "./package.json";

/**
 * MV3 manifest.
 *
 * PERMISSIONS ARE DELIBERATELY MINIMAL. Each one below is justified; anything
 * not justified is not requested.
 */
export default defineManifest({
  manifest_version: 3,
  name: "Wallet",
  version: packageJson.version,
  description: "A non-custodial Ethereum wallet.",

  // storage   — the encrypted vault and user settings.
  // alarms    — auto-lock that survives service-worker termination (setTimeout
  //             cannot, see background/lockPolicy.ts).
  // scripting — programmatic injection of the inpage provider.
  //
  // NOT requested: "tabs" (we only need the active tab's origin, which the
  // content-script port already gives us), "webRequest", "cookies", "history",
  // "downloads", "clipboardRead". A wallet asking for any of those should
  // raise questions, so we ask for none.
  permissions: ["storage", "alarms", "scripting"],

  background: {
    service_worker: "src/background/serviceWorker.ts",
    /**
     * Firefox does not implement `background.service_worker` at all
     * (bugzil.la/1573659) — it runs MV3 background code as an EVENT PAGE via
     * `background.scripts`. Declaring both is the documented cross-browser
     * form: Chrome reads `service_worker` and ignores `scripts`, Firefox does
     * the reverse. Firefox 121+ starts the event page correctly even when
     * `service_worker` is also present.
     *
     * NOTE: this makes the manifest loadable in Firefox, but it does NOT make
     * the lock model equivalent. Our entire "SW termination == wallet locked"
     * guarantee rests on Chrome tearing the worker down; an event page has a
     * different lifetime. See background/lockPolicy.ts before trusting this on
     * Firefox.
     */
    scripts: ["src/background/serviceWorker.ts"],
    type: "module",
  },

  /**
   * ICONS. Generated by `scripts/generateIcons.mjs`, checked in under
   * `public/icons/` -- Vite copies `public/` verbatim into `dist/`, so these
   * paths are correct in the built manifest as written.
   *
   * Both keys are required, and for different reasons. `icons` is the
   * extensions page, the permissions dialog and the Chrome Web Store listing --
   * a submission without a 128 is rejected outright. `action.default_icon` is
   * the toolbar button; omit it and Chrome substitutes a grey square holding
   * the first letter of the name, which for an extension called "Wallet" is a
   * grey "W" sitting next to the user's real wallet. Looking like an
   * unfinished extension is a security problem in this category and not
   * merely an aesthetic one: users identify the genuine wallet by its mark,
   * and an impostor is free to ship a nicer one.
   */
  icons: {
    16: "icons/icon-16.png",
    32: "icons/icon-32.png",
    48: "icons/icon-48.png",
    128: "icons/icon-128.png",
  },

  action: {
    default_popup: "src/ui/popup/index.html",
    default_title: "Wallet",
    default_icon: {
      16: "icons/icon-16.png",
      32: "icons/icon-32.png",
      48: "icons/icon-48.png",
      128: "icons/icon-128.png",
    },
  },

  options_page: "src/ui/onboarding/index.html",

  /**
   * HOST PERMISSIONS — THE UNAVOIDABLE PRIVACY TRADE-OFF.
   *
   * dApps expect `window.ethereum` to exist the moment their page loads, on
   * any domain. Serving that expectation means injecting into every site,
   * which means <all_urls>. There is no narrower grant that preserves the
   * behaviour users expect from a wallet.
   *
   * What we do to limit the blast radius:
   *   - The injected provider is inert until the user approves the origin.
   *   - The content script forwards messages and holds no secrets, ever.
   *   - No page content is read, and nothing is transmitted anywhere.
   *
   * `optional_host_permissions` is the privacy-maximising alternative: ship
   * with no host access and let the user grant per-site. Strictly better for
   * privacy, strictly worse for first-run UX, because a dApp that loads before
   * the grant sees no wallet at all. Flagged as a deliberate product decision
   * rather than an oversight — see the README trade-off note.
   */
  host_permissions: ["<all_urls>"],

  content_scripts: [
    {
      matches: ["<all_urls>"],
      js: ["src/content/contentScript.ts"],
      // ISOLATED world: the bridge runs in the extension's own context, so
      // page scripts cannot monkey-patch it or read what passes through it.
      world: "ISOLATED",
      run_at: "document_start",
      all_frames: false,
    },
    {
      matches: ["<all_urls>"],
      js: ["src/inpage/provider.ts"],
      /**
       * MAIN world: the provider must live in the page's own realm, because
       * `window.ethereum` has to be reachable by page scripts.
       *
       * Declaring it as a MAIN-world content script (Chrome 111+) rather than
       * shipping it via `web_accessible_resources` + a <script> tag is both
       * simpler and safer:
       *   - the bundler compiles it like any other entry, so it cannot ship as
       *     raw TypeScript,
       *   - it runs at document_start before page scripts, so dApps never
       *     observe a missing provider and race us,
       *   - no injected <script> element, which some page CSPs would block.
       */
      world: "MAIN",
      run_at: "document_start",
      all_frames: false,
    },
  ],

  /**
   * MV3 forbids remote code by default; we state the policy explicitly so it
   * is visible in review. 'self' only: no CDN scripts, no eval, no inline
   * handlers. Everything ships in the bundle, which is what makes the
   * dependency tree the whole of our supply-chain surface.
   */
  content_security_policy: {
    extension_pages: "script-src 'self'; object-src 'self'",
  },

  minimum_chrome_version: "116",
});
